let shopItemsData = [
  {
    id: "Producto1",
    name: "BOMBAY SAPPHIRE",
    price: 20.00,
    desc: "Ginebra Infusionada <br> Botella 700 ml",
    img: "/img/products/bombay.png",
    },
    {
      id: "Producto2",
      name: "JAGERMEISTER",
      price: 29.80,
      desc: "Licor de Hierbas <br> Botella 1.75 L",
      img: "/img/products/jager.png",
    },
    {
      id: "Producto3",
      name: "JOHNINIE WALKER",
      price: 189.30,
      desc: "Blue Label Whisky <br> Botella 700 ml",
      img: "/img/products/bluelabel.png",
    },
    {
      id: "Producto4",
      name: "JACK DANIEL´S",
      price: 25.00,
      desc: "Tennesseee Whiskey  <br> Botella 1 L",
      img: "/img/products/jackdaniels.png",
    },
    {
      id: "Producto5",
      name: "JOHNINIE WALKER",
      price: 15.99,
      desc: "Red Label Whisky <br> Botella 700 ml",
      img: "/img/products/redlabel.png",
    },
    {
      id: "Producto6",
      name: "HIBIKI",
      price: 95.00,
      desc: "Hibiki Harmony Suntory <br> Botella 750 ml",
      img: "/img/products/hibiki.png",
    },   {
      id: "Producto7",
      name: "CROWN ROYAL",
      price: 780.00,
      desc: "Extra XR Rare <br> Botella 700 ml",
      img: "/img/products/crownxr.png",
    },
    {
      id: "Producto8",
      name: "MONKEY SHOULDER",
      price: 28.09,
      desc: "Malt Scoth Whisky Premium <br> Botella 700 ml",
      img: "/img/products/monkey.png",
    },
    {
      id: "Producto9",
      name: "JACK DANIEL´S",
      price: 23.45,
      desc: " Honey Tennesseee Whiskey <br> Botella 700 ml",
      img: "/img/products/jackdanielshoney.png",
    },
    {
      id: "Producto10",
      name: "DALMORE TRINITAS",
      price: 140500.00,
      desc: "64 Year Old Malt Scoth Whisky <br> Botella 1.5 L",
      img: "/img/products/dalmore.png",
    },
    {
      id: "Producto11",
      name: "JOHNINIE WALKER",
      price: "CONSULTAR",
      desc: "Sons Diamond Jubilee <br> Botella 700 ml",
      img: "/img/products/diamondjubilee.png",
    },
    {
      id: "Producto12",
      name: "LAGAVULIN",
      price: 105,
      desc: "16 Year Old Malt Scoth Whisky <br> Botella 700 ml",
      img: "/img/products/whisky.png",
    },
  ];
  